FROM python:3.7

COPY . /backend

WORKDIR /backend

ENV FLASK_RUN_PORT 5000
ENV FLASK_APP app.py
ENV FLASK_DEBUG 1

RUN pip install --upgrade pip

RUN pip install -r ./requirements.txt

# CMD [ "flask run --host=0.0.0.0" ]
